name: logic
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/spudilalka/chess-chekers-logic.git

environment:
  sdk: '>=2.18.7 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
